import React from 'react';
import { Language } from './types';

export const TEXTS = {
  en: {
    appName: "ArthaSetu",
    tagline: "Your Friend in Banking",
    welcome: "Welcome to ArthaSetu",
    landingLogin: "I have an account (Login)",
    landingSignup: "I am new here (Sign Up)",
    loginTitle: "Login to Your Account",
    accIdLabel: "Bank Account ID",
    enterPin: "Enter 4-Digit PIN",
    loginBtn: "Enter Bank",
    signup: "New User Register",
    name: "Full Name",
    mobile: "Mobile Number",
    pin: "Set 4-Digit PIN",
    registerBtn: "Create My Account",
    signupSuccess: "Account Created!",
    saveIdMsg: "This is your Bank ID. Please write it down or take a photo.",
    balance: "Your Balance",
    sendMoney: "Send Money",
    receiveMoney: "My Bank ID",
    lastFive: "Recent History",
    changePin: "Change PIN",
    profile: "My Profile",
    help: "Get Help",
    emergency: "Block My Account",
    confirmTransfer: "Send to",
    amount: "How much?",
    enterId: "Enter Receiver ID",
    validateId: "Checking ID...",
    idFound: "Name Found:",
    invalidFormat: "ID format is wrong. Please check and try again.",
    success: "Success!",
    done: "Done",
    voicePrompt: "Speak now...",
    cancel: "Cancel",
    confirm: "Yes, Correct",
    back: "Go Back",
    logout: "Exit App",
    idFormatHint: "Example: BANK-KA-2026-123456",
    wrongPin: "Wrong PIN. Please try again.",
    billPay: "Bills & Recharge",
    loans: "Loan Info",
    reportTitle: "Monthly Report",
    reportSaved: "Money Saved",
    reportSpent: "Money Spent"
  },
  kn: {
    appName: "ಅರ್ಥಸೇತು (ArthaSetu)",
    tagline: "ಬ್ಯಾಂಕಿಂಗ್‌ನಲ್ಲಿ ನಿಮ್ಮ ಸ್ನೇಹಿತ",
    welcome: "ಅರ್ಥಸೇತುಗೆ ಸ್ವಾಗತ",
    landingLogin: "ನನಗೆ ಈಗಾಗಲೇ ಖಾತೆ ಇದೆ (ಲಾಗಿನ್)",
    landingSignup: "ನಾನು ಹೊಸಬ (ನೋಂದಣಿ)",
    loginTitle: "ನಿಮ್ಮ ಖಾತೆಗೆ ಲಾಗಿನ್ ಮಾಡಿ",
    accIdLabel: "ಬ್ಯಾಂಕ್ ಐಡಿ ನಮೂದಿಸಿ",
    enterPin: "4-ಅಂಕಿಯ ಪಿನ್ ನಮೂದಿಸಿ",
    loginBtn: "ಬ್ಯಾಂಕ್ ಪ್ರವೇಶಿಸಿ",
    signup: "ಹೊಸ ಬಳಕೆದಾರ ನೋಂದಣಿ",
    name: "ಪೂರ್ಣ ಹೆಸರು",
    mobile: "ಮೊಬೈಲ್ ಸಂಖ್ಯೆ",
    pin: "4-ಅಂಕಿಯ ಪಿನ್ ಸೆಟ್ ಮಾಡಿ",
    registerBtn: "ಖಾತೆ ತೆರೆಯಿರಿ",
    signupSuccess: "ಖಾತೆ ತೆರೆಯಲಾಗಿದೆ!",
    saveIdMsg: "ಇದು ನಿಮ್ಮ ಬ್ಯಾಂಕ್ ಐಡಿ. ದಯವಿಟ್ಟು ಇದನ್ನು ಬರೆದಿಟ್ಟುಕೊಳ್ಳಿ.",
    balance: "ನಿಮ್ಮ ಬ್ಯಾಲೆನ್ಸ್",
    sendMoney: "ಹಣ ಕಳುಹಿಸಿ",
    receiveMoney: "ನನ್ನ ಬ್ಯಾಂಕ್ ಐಡಿ",
    lastFive: "ಇತ್ತೀಚಿನ ವಹಿವಾಟು",
    changePin: "ಪಿನ್ ಬದಲಾಯಿಸಿ",
    profile: "ನನ್ನ ಪ್ರೊಫೈಲ್",
    help: "ಸಹಾಯ",
    emergency: "ಖಾತೆ ಬ್ಲಾಕ್ ಮಾಡಿ",
    confirmTransfer: "ಕಳುಹಿಸಬೇಕಾದ ವ್ಯಕ್ತಿ",
    amount: "ಎಷ್ಟು ಹಣ?",
    enterId: "ಸ್ವೀಕರಿಸುವವರ ಐಡಿ ನಮೂದಿಸಿ",
    validateId: "ಪರಿಶೀಲಿಸಲಾಗುತ್ತಿದೆ...",
    idFound: "ಹೆಸರು ಸಿಕ್ಕಿದೆ:",
    invalidFormat: "ಐಡಿ ಫಾರ್ಮ್ಯಾಟ್ ತಪ್ಪಾಗಿದೆ. ದಯವಿಟ್ಟು ಪರಿಶೀಲಿಸಿ.",
    success: "ಯಶಸ್ವಿಯಾಗಿದೆ!",
    done: "ಮುಗಿಯಿತು",
    voicePrompt: "ಈಗ ಮಾತನಾಡಿ...",
    cancel: "ರದ್ದುಮಾಡಿ",
    confirm: "ಹೌದು, ಸರಿಯಾಗಿದೆ",
    back: "ಹಿಂದಕ್ಕೆ ಹೋಗಿ",
    logout: "ಬ್ಯಾಂಕ್‌ನಿಂದ ಹೊರಬನ್ನಿ",
    idFormatHint: "ಮಾದರಿ: BANK-KA-2026-123456",
    wrongPin: "ಪಿನ್ ತಪ್ಪಾಗಿದೆ. ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.",
    billPay: "ಬಿಲ್ ಪಾವತಿ",
    loans: "ಸಾಲದ ಮಾಹಿತಿ",
    reportTitle: "ಮಾಸಿಕ ವರದಿ",
    reportSaved: "ಉಳಿತಾಯ",
    reportSpent: "ವೆಚ್ಚ"
  },
  hi: {
    appName: "अर्थसेतु (ArthaSetu)",
    tagline: "ಬ್ಯಾಂಕಿಂಗ್‌ನಲ್ಲಿ ನಿಮ್ಮ ಸ್ನೇಹಿತ",
    welcome: "अर्थसेतु में आपका स्वागत है",
    landingLogin: "मेरा पहले से खाता है (लॉगिन)",
    landingSignup: "मैं नया हूँ (साइन अप)",
    loginTitle: "अपने खाते में लॉगिन करें",
    accIdLabel: "बैंक आईडी डालें",
    enterPin: "4-अंकों का पिन डालें",
    loginBtn: "बैंक में प्रवेश करें",
    signup: "नया यूजर रजिस्टर करें",
    name: "पूरा नाम",
    mobile: "मोबाइल नंबर",
    pin: "4-अंकों का पिन सेट करें",
    registerBtn: "खाता खोलें",
    signupSuccess: "खाता खुल गया है!",
    saveIdMsg: "यह आपकी बैंक आईडी है। इसे लिखकर रख लें।",
    balance: "आपका बैलेंस",
    sendMoney: "पैसे भेजें",
    receiveMoney: "मेरी बैंक आईडी",
    lastFive: "हाल के लेनदेन",
    changePin: "पिन बदलें",
    profile: "मेरी प्रोफाइल",
    help: "मदद लें",
    emergency: "खाता ब्लॉक करें",
    confirmTransfer: "किसको भेजना है?",
    amount: "कितने पैसे?",
    enterId: "रिसीवर की आईडी डालें",
    validateId: "आईडी चेक हो रही है...",
    idFound: "नाम मिल गया:",
    invalidFormat: "आईडी फॉर्मेट गलत है। कृपया फिर से जांचें।",
    success: "सफल हुआ!",
    done: "हो गया",
    voicePrompt: "अब बोलें...",
    cancel: "रद्द करें",
    confirm: "हाँ, सही है",
    back: "पीछे जाएं",
    logout: "ऐप से बाहर निकलें",
    idFormatHint: "प्रारूप: BANK-KA-2026-123456",
    wrongPin: "पिन गलत है। फिर से कोशिश करें.",
    billPay: "बिल भुगतान",
    loans: "ऋण जानकारी",
    reportTitle: "मासिक रिपोर्ट",
    reportSaved: "बचत",
    reportSpent: "खर्च"
  }
};

export const COLORS = {
  primary: 'bg-emerald-600',
  secondary: 'bg-amber-500',
  accent: 'bg-blue-600',
  danger: 'bg-red-500',
  bgGradient: 'from-emerald-50 to-emerald-100'
};